### ISSUE TITLE
Verification for large files

### ISSUE THREAD

**Issue by potvik** [harmony-one/contract-verification-service#6]
Verification for large files

Right now we send solidity sources via http request. It has limits. So users have problems with large contract sources.

Solution: We should to add file loader and load file to service. Like on etherscan.

**Comment by victaphu** [comment]
Duplicate of https://github.com/harmony-one/explorer-v2-frontend/issues/115
Closing this one and tracking using https://github.com/harmony-one/explorer-v2-frontend/issues/115

**Comment by victaphu** [comment]
@potvik  please close this
